#!/bin/sh

SCULL_LOAD=/usr/bin/scull_load
MODULE_LOAD=/usr/bin/module_load
SCULL_UNLOAD=/usr/bin/scull_unload
MODULE_UNLOAD=/usr/bin/module_unload

case "$1" in
  start)
    cd /etc/init.d || exit 1
    [ -x "$SCULL_LOAD" ] && "$SCULL_LOAD"
    [ -x "$MODULE_LOAD" ] && "$MODULE_LOAD" faulty
    lsmod | grep -q "hello" || modprobe hello
    ;;
  stop)
    lsmod | grep -q "hello" && rmmod hello
    [ -x "$MODULE_UNLOAD" ] && "$MODULE_UNLOAD" faulty
    [ -x "$SCULL_UNLOAD" ] && "$SCULL_UNLOAD"
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0

